# Github workflow to compile latex and deploy the pdf to an orphan branch.
# The latest compiled pdf is at available at e.g.
# https://github.com/dgerosa/reponame/blob/build/filename.pdf
# Davide Gerosa (2021) https://github.com/dgerosa

name: deployfca
on: [push]
jobs:
  documentation:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: work
      FILE: source/latex/fca/latex-fca.dtx
      PDFFILE: latex-fca.pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install TeXlive
        run: sudo apt-get -y update && sudo apt-get -y install texlive texlive-publishers texlive-science latexmk cm-super
      - name: Make working directory
        run: mkdir -p ${{ env.DIR }} && cp ${{ env.FILE }} ${{ env.DIR }}
      - name: LaTeX compile
        working-directory: ${{ env.DIR }}
        run: TEXMFHOME=${PWD} latexmk -pdf -bibtex $(basename ${{ env.FILE }} )
      - name: Compile notikzfca
        working-directory: doc/latex/fca
        run: TEXMFHOME=${PWD} latexmk -pdf -bibtex notikzfca
        #run: pdflatex ${{ env.FILE }}; bibtex ${{ env.FILE }}; pdflatex ${{ env.FILE }}; pdflatex ${{ env.FILE }};
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.PDFFILE }} doc/latex/fca/notikzfca.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu_latest_pdfs
          path: ./github_artifacts
  debian_stable:
    runs-on: ubuntu-latest
    container: debian:stable
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: work
      FILE: source/latex/fca/latex-fca.dtx
      PDFFILE: latex-fca.pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install TeXlive
        run: apt-get -y update && apt-get -y install texlive texlive-publishers texlive-science latexmk cm-super
      - name: Make working directory
        run: mkdir -p ${{ env.DIR }} && cp ${{ env.FILE }}  ${{ env.DIR }}
      - name: LaTeX compile
        working-directory: ${{ env.DIR }}
        run: TEXMFHOME=${PWD} latexmk -pdf -bibtex $(basename ${{ env.FILE }} )
      - name: Compile notikzfca
        working-directory: doc/latex/fca
        run: TEXMFHOME=${PWD} latexmk -pdf -bibtex notikzfca
        #run: pdflatex ${{ env.FILE }}; bibtex ${{ env.FILE }}; pdflatex ${{ env.FILE }}; pdflatex ${{ env.FILE }};
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.PDFFILE }}  doc/latex/fca/notikzfca.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Debian_stable_pdfs
          path: ./github_artifacts
  deploy:
    # Edit here if compiling multiple papers
    needs: [documentation]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
